config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :challenges do
    resources :benefits, only: [:new, :create, :show, :index]
    resources :fears, only: [:new, :create, :show, :destroy]
  end
  resources :fears, only: [:show] do
    resources :preventions, only: [:new, :create, :show, :destroy]
    resources :fixes, only: [:new, :create, :show, :destroy]  
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :challenges, only: [ :index, :show, :update, :create ]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/benefit.rb
class Benefit < ApplicationRecord
    belongs_to :challenge
end

app/models/challenge.rb
class Challenge < ApplicationRecord
    belongs_to :user
    has_many :fears, dependent: :destroy
    has_many :benefits, dependent: :destroy
    has_many :preventions, through: :fear 
    has_many :fixes, through: :fear
    has_one :benefit
    accepts_nested_attributes_for :benefit
end

app/models/fear.rb
class Fear < ApplicationRecord
    belongs_to :challenge
    has_many :preventions, dependent: :destroy
    has_many :fixes, dependent: :destroy
    accepts_nested_attributes_for :fixes, :preventions
end

app/models/fix.rb
class Fix < ApplicationRecord
    belongs_to :fear
end

app/models/prevention.rb
class Prevention < ApplicationRecord
    belongs_to :fear
end

app/models/user.rb
class User < ApplicationRecord
  # acts_as_token_authenticatable
  has_many :challenges, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from StandardError,                with: :internal_server_error
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end

  def internal_server_error(exception)
    if Rails.env.development?
      response = { type: exception.class.to_s, message: exception.message, backtrace: exception.backtrace }
    else
      response = { error: "Internal Server Error" }
    end
    render json: response, status: :internal_server_error
  end
end

app/controllers/api/v1/challenges_controller.rb
class Api::V1::ChallengesController < Api::V1::BaseController
  acts_as_token_authentication_handler_for User

  def index
    @challenges = Challenge.where(user_id: current_user)
  end

  def show
    @challenge = Challenge.find(params[:id])
    @benefits = Benefit.where(challenge_id: @challenge.id)
    @fears = Fear.where(challenge_id: @challenge.id)
  end

  def update
    if @challenge.update(challenge_params)
      render :show
    else
      render_error
    end
  end

  private

  def challenge_params
    params.require(:challenge).permit(:description, :name, :acceptable, :cost_inaction_hy, :cost_inaction_yr, :cost_inaction3y, :user_id, {:benefit_attributes => [:description]})
  end

  def render_error
    render json: { errors: @challenge.errors.full_messages },
      status: :unprocessable_entity
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    @user = current_user
    challenges_path
  end
end

app/controllers/benefits_controller.rb
class BenefitsController < ApplicationController
    def new
        @challenge = Challenge.find(params[:challenge_id])
        @fears = Fear.where(challenge_id: params[:challenge_id])
        @benefits = Benefit.where(challenge_id: params[:challenge_id])
        @benefit = Benefit.new
      end

    def create
        @benefit = Benefit.new(benefit_params)
        @benefit.challenge_id = params[:challenge_id]
        @benefit.save!
        redirect_to new_challenge_benefit_path
    end
    
    private

    def benefit_params
        params.require(:benefit).permit(:description, :challenge_id)
    end    
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
    def index
        @challenges = Challenge.where(user_id: current_user)
        # @challenges.each do |c|
        #   @benefits = Benefit.where(challenge_id: c.id)
        #   @fears = Fear.where(challenge_id: c.id)
        # end
    end

    def show
        @challenge = Challenge.find(params[:id])
        @benefits = Benefit.where(challenge_id: @challenge.id)
        @fears = Fear.where(challenge_id: @challenge.id)
    end

    def new
        @challenge = Challenge.new
    end

    def create
        @challenge = Challenge.new(challenge_params)
        @challenge.user = current_user
        # get benefit
        # get fear (and sub preventions and fixes)
        # get consequences of inaction
        @challenge.save!
        redirect_to new_challenge_benefit_path(@challenge)
    end

    def edit
      @challenge = Challenge.find(params[:id])
    end

    def update
      @challenge = Challenge.find(params[:id])
      @challenge.update(challenge_params)
      redirect_to challenges_path
    end

    def destroy
      @challenge = Challenge.find(params[:id])
      @challenge.destroy
      redirect_to root_path
    end

    private

    def challenge_params
        params.require(:challenge).permit(:description, :name, :acceptable, :cost_inaction_hy, :cost_inaction_yr, :cost_inaction3y, :user_id, {:benefit_attributes => [:description]})
    end
end

app/controllers/fears_controller.rb
class FearsController < ApplicationController
    def create
        @fear = Fear.new(fear_params)
        @fear.challenge_id = params[:challenge_id]
        @fear.save!
        redirect_to new_challenge_benefit_path
    end

    private

    def fear_params
        params.require(:fear).permit(:description, :challenge_id)
    end  
end

app/controllers/fixes_controller.rb
class FixesController < ApplicationController
    def new
        @fear = Fear.find(params[:fear_id])
        @fixes = Fix.where(fear_id: params[:fear_id])
        @preventions = Prevention.where(fear_id: params[:fear_id])
        @fix = Fix.new
    end

    def create
        @fix = Fix.new(fix_params)
        @fix.fear_id = params[:fear_id]
        @fix.save!
        redirect_to new_fear_fix_path
    end

    private

    def fix_params
        params.require(:fix).permit(:description, :fear_id)
    end       
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @challenge = Challenge.new
  end
end

app/controllers/preventions_controller.rb
class PreventionsController < ApplicationController
    def new
        @fear = Fear.find(params[:fear_id])
        @preventions = Prevention.where(fear_id: params[:fear_id])
        @fixes = Fix.where(fear_id: params[:fear_id])
        @prevention = Prevention.new
    end

    def create
        @prevention = Prevention.new(prevention_params)
        @prevention.fear_id = params[:fear_id]
        @prevention.save!
        redirect_to new_fear_prevention_path
    end

    private

    def prevention_params
        params.require(:prevention).permit(:description, :fear_id)
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
    def setup_challenge(challenge)
      challenge.benefit ||= Benefit.new
      challenge
    end
  end

app/views/benefits/new.html.erb
<div class="kop">
<h1>Fear-Setting</h1>
<p>inspired by Tim Ferris' TED Talk</p>
</div>
Challenge: 
<div class="challenge">
    <%= @challenge.description %>
</div>

<% if @benefits %>
Benefits:
    <% @benefits.each do |b| %>
        <div class="textbox">
            <%= b.description %>
        </div>
    <% end %>
<% end %>
<br />

<%= form_for(Benefit.new, as: :benefit, url: challenge_benefits_path) do |f| %>
    New Benefit: <br />
    <%= f.text_field :description, required: true, autofocus: true, class: "input_textbox" %>
    <div class="form-actions">
        <%= f.submit "add benefit", class: 'knop-1' %>
    </div>
<% end %>

<% if @fears %>
Fears:
    <% @fears.each do |f| %>
        <div class="textbox">
            <%= f.description %>
            <button class="knop-1"><%= link_to "Prevention", new_fear_prevention_path(f) %></button>
        </div>
       
    <% end %>
<% end %>
<br />

<%= form_for(Fear.new, as: :fear, url: challenge_fears_path) do |f| %>
    New Fear: <br />
    <%= f.text_field :description, required: true, class: "input_textbox" %>
    <div class="form-actions">
        <%= f.submit "add fear", class: 'knop-1' %>
    </div>
<% end %>

app/views/challenges/edit.html.erb
<div class="kop">
<h1>Fear-Setting</h1>
<h4>inspired by Tim Ferris' TED Talk</h4>
</div>

<%= simple_form_for(@challenge) do |c| %>
  <%= c.error_notification %>

  <div class="form-inputs">
    <%= c.input :cost_inaction_hy %>
    <%= c.input :cost_inaction_yr %>
    <%= c.input :cost_inaction_3y %>
    <%= c.label "Are these acceptable?" %>
    <%= c.check_box :acceptable %>
  </div>

  <div class="form-actions">
    <%= c.button :submit %>
  </div>
<% end %>

app/views/challenges/index.html.erb
<div class="kop">
<h1>Fear-Setting</h1>
<h4>inspired by Tim Ferris' TED Talk</h4>
</div>
Your Challenges:
<% @challenges.each do |c| %>
    <div class="challenge">
      <%= c.description %>
    </div>
    Can you accept the consequences of not taking action?
    <div class="challenge">
      <% if c.acceptable %>
        Yes
      <% else %>
        No: Begin now!
      <% end %>
    </div
  <button class="knop-1"><%= link_to "Challenge Details", challenge_path(c) %></button>
<% end %>

app/views/challenges/show.html.erb
<div class="kop">
<h1>Fear-Setting</h1>
<h4>inspired by Tim Ferris' TED Talk</h4>
</div>
<div container>
    <div row>
        <div class="col-xs-6 col-sm-6">
            Challenge:
            <div class="challenge">
                <%= @challenge.description %>
            </div>
        </div>
        <div class="col-xs-6 col-sm-6">
            Is taking no action acceptable?
            <div class="challenge">
                <% if @challenge.acceptable %>
                Yes
                <% else %>
                No: Begin now!
                <% end %>
            </div>
        </div>
    </div>
</div>
<div container>
    <div row>
        <div class="col-xs-6 col-sm-6">
            Benefits:
            <% @benefits.each do |b| %>
                <div class="textbox">
                    <%= b.description %>
                </div>
            <% end %>
              Consequences:
            <div class="textbox">
                6 months from now: <%= @challenge.cost_inaction_hy %>
            </div>
            <div class="textbox">
                1 year from now: <%= @challenge.cost_inaction_yr %>
            </div>
            <div class="textbox">
                3 years from now: <%= @challenge.cost_inaction_3y %>
            </div>
            <button class="knop-1"><%= link_to "Acceptable?", edit_challenge_path(@challenge) %></button>
        </div>
        <div class="col-xs-6 col-sm-6">
            Fears:
            <% @fears.each do |f| %>
                <div class="textbox">
                    <%= f.description %>
                    <br />
                    Preventions:
                    <% Prevention.where(fear_id: f.id).each do |p| %>
                        <div class="textbox-2">
                            <%= p.description %>
                        </div>
                    <% end %>
                    Fixes:
                    <% Fix.where(fear_id: f.id).each do |f| %>
                        <div class="textbox-2">
                            <%= f.description %>
                        </div>
                    <% end %>                    
                </div>
            <% end %>
        </div>
    </div>
</div>

  <button class="knop-1"><%= link_to "Edit Consequences", edit_challenge_path(@challenge) %></button>

app/views/fixes/new.html.erb
<div class="kop">
<h1>Fear-Setting</h1>
<h4>inspired by Tim Ferris' TED Talk</h4>
</div>

Fear = 
<div class="challenge">
    <%= @fear.description %>
</div>
<% if @fixes %>
fixes:
    <% @fixes.each do |f| %>
        <div class="textbox">
            <%= f.description %>
        </div>
    <% end %>
<% end %>
<br />

<%= form_for(Fix.new, as: :fix, url: fear_fixes_path) do |f| %>
    <%= f.text_field :description, required: true, autofocus: true, class: "input_textbox" %>
    <div class="form-actions">
        <%= f.submit "add fix", class: 'knop-1' %>
    </div>
<% end %>

Preventions:
<% @preventions.each do |p| %>
    <div class="textbox">
        <%= p.description %>
    </div>
<% end %>
<br />
<button class="knop-1"><%= link_to "Add Prevention", new_fear_prevention_path(@fear) %></button>
<button class="knop-1"><%= link_to "Show Challenge", challenges_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Fear-Setting</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag %>
  </head>
  <body background>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="wrapper">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="kop">
<h1>Fear-Setting</h1>
<h4>inspired by Tim Ferris' TED Talk</h4>
</div>

<%#= form_for(Challenge.new, as: :challenge, url: challenges_path) do |f| %>
<%= form_for(setup_challenge(@challenge)) do |f| %>
    Challenge: <br />
    <%= f.text_field :description, required: true, autofocus: true, class: "input_textbox" %>
    <%= f.fields_for :benefit do |b| %> 
       <br />Benefit: <br />
       <%= b.text_field :description, class: "input_textbox" %>
    <% end %>
    <div class="form-actions">
        <%= f.submit "Next", class: 'knop-1' %>
    </div>
<% end %>

app/views/preventions/new.html.erb
<div class="kop">
<h1>Fear-Setting</h1>
<h4>inspired by Tim Ferris' TED Talk</h4>
</div>
Fear = 
<div class="challenge">
<%= @fear.description %>
</div>

<% if @preventions %>
Preventions:
    <% @preventions.each do |p| %>
        <div class="textbox">
            <%= p.description %>
        </div>
    <% end %>
<% end %>
<br />

<%= form_for(Prevention.new, as: :prevention, url: fear_preventions_path) do |p| %>
    <%= p.text_field :description, required: true, autofocus: true, class: "input_textbox" %>
    <div class="form-actions">
        <%= p.submit "add prevention", class: 'knop-1' %>
    </div>
<% end %>

Fixes:
<% @fixes.each do |f| %>
    <br />
    <%= f.description %>
<% end %>

<br />
<button class="knop-1"><%= link_to "Add Fix", new_fear_fix_path(@fear) %></button>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "lightning.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Login",  new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "lightning.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to challenges_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Challenges") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Login",  new_user_session_path %></li>
        <li><%= link_to "Your Challenges",  challenges_path %></li>
      </ul>
    </div>
  </div>
</div>